Repository AY1920S2-CS2113T-T12-4/tp, pull requests merged in 2020-04, with the labels that each got.

#153 UserGuide - Reformat
  docs/UserGuide.md
Labels: Documentation

#155 Attendance - Added Attendance Parser
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/parser/AttendanceParser.java
Labels: type.Bug

#157 Student List, Attendance - Student Attendance Link
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/student/StudentListCollection.java
Labels: feature.edit

#154 Student List - Student Command to Student.List
  docs/UserGuide.md
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/ui/Help.java
Labels: Documentation, severity.VeryLow, type.Bug

#152 Attendance - status bug
  docs/UserGuide.md
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
Labels: type.Bug

#159 Student List - No Duplicate
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/student/AddStudentList.java
  src/main/java/seedu/student/StudentList.java
  src/main/java/seedu/student/StudentListCollection.java
  src/main/java/seedu/ui/UI.java
Labels: feature.edit

#156 Student List - Student Find Speed Up
  src/main/java/seedu/command/student/FindStudentList.java
Labels: feature.edit

#160 Event-related fix
  .gitignore
  data/eventlist.txt
  data/studentlist.txt
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/EventCommandInterpreter.java
  src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java
  src/main/java/seedu/parser/EventParser.java
Labels: severity.VeryLow

#158 Storage-related fix
  src/main/java/seedu/storage/FileIO.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#162 Event editing bugs fixed and datetime not set to localtime anymore
  src/main/java/seedu/command/calendar/CalendarList.java
  src/main/java/seedu/command/event/AddEvent.java
  src/main/java/seedu/command/interpreter/CalendarCommandInterpreter.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/ui/UI.java
Labels: error handling, type.Bug

#164 Anqi - editPerformance
  src/main/java/seedu/command/interpreter/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformance.java
  src/main/java/seedu/command/performance/DeletePerformance.java
  src/main/java/seedu/command/performance/EditPerformance.java
  src/main/java/seedu/command/performance/ViewStudentPerformance.java
  src/main/java/seedu/command/student/SortStudentListByName.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/Help.java
  src/main/java/seedu/ui/UI.java
Labels: feature.new

#161 Attendance SLAP
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/ClearAttendanceList.java
  src/main/java/seedu/command/attendance/SortAttendanceListByName.java
  src/main/java/seedu/command/attendance/SortAttendanceListByStatus.java
  src/main/java/seedu/command/attendance/ViewAttendanceList.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/parser/AttendanceParser.java
Labels: Code Quality

#165 Add PPP
  docs/team/lowjiayee.md
Labels: Documentation

#172 Change pics of terminal in UG
  docs/UserGuide.md
  docs/images/Startupscreen.PNG
  docs/images/filepath.PNG
  docs/images/startup.PNG
Labels: Documentation

#174 Add PPP draft
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/harithadiv.md
Labels: Documentation

#176 PPP template
  docs/team/benchan911.md
Labels: Documentation

#175 updated benchan911 PPP
  docs/team/benchan911.md
Labels: Documentation

#178 Anqi - Update help, DG diagram and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Performance.png
  docs/images/Ui.png
  docs/team/anqi-nus.md
  docs/team/johndoe.md
  src/main/java/seedu/command/Help.java
  src/main/java/seedu/command/interpreter/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformanceList.java
  src/main/java/seedu/command/performance/DeletePerformanceList.java
  src/main/java/seedu/command/performance/EditPerformanceList.java
  src/main/java/seedu/command/performance/SortPerformanceListByName.java
  src/main/java/seedu/command/performance/SortPerformanceListByResult.java
  src/main/java/seedu/command/performance/ViewStudentPerformanceList.java
  src/main/java/seedu/exception/PerformanceAssignmentListException.java
  src/main/java/seedu/exception/PerformanceStudentListException.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/Help.java
  src/main/java/seedu/ui/UI.java
Labels: Documentation, feature.edit

#182 Fix AttendanceList Bug
  src/main/java/seedu/attendance/AttendanceList.java
Labels: type.Bug

#183 fix student help
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/ui/Help.java
Labels: type.Bug

#190 Benjamin v2.1 error handling
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/ClearAttendanceList.java
  src/main/java/seedu/command/attendance/ViewAttendanceList.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/attendance/AttendanceTest.java
Labels: error handling

#167 Update DG diagram
  docs/DeveloperGuide.md
  docs/images/Architecture.png
  docs/images/Event.png
  docs/images/EventSequence.png
  docs/images/event.png
  src/main/java/seedu/command/event/AddEvent.java
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/student/SortStudentListByName.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/storage/FileIO.java
  src/test/java/seedu/performance/PerformanceListTest.java
Labels: Documentation

#194 Matching UserGuide to Attendance and StudentList
  docs/UserGuide.md
  docs/images/filepath.png
  docs/images/logo.png
  docs/images/startup.png
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/EditAttendance.java
  src/main/java/seedu/command/attendance/FindAttendance.java
  src/main/java/seedu/command/student/AddStudentList.java
  src/main/java/seedu/command/student/ClearStudentList.java
  src/main/java/seedu/command/student/DeleteStudentList.java
  src/main/java/seedu/command/student/FindStudentList.java
  src/main/java/seedu/command/student/SortStudentListByList.java
  src/main/java/seedu/command/student/SortStudentListByName.java
  src/main/java/seedu/command/student/ViewStudentList.java
  src/main/java/seedu/ui/UI.java
Labels: Documentation

#192 Update DG diagram.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddPerformance.png
  docs/images/DeletePerformance.png
  docs/images/EditPerformance.png
  docs/images/Performance.png
  docs/images/PerformanceCommandInterpreterFlowChart.png
  docs/images/PerformanceCommandInterpreterSequenceDiagram.png
  docs/images/SortPerformanceList.png
  docs/images/SortPerformanceListByResult.png
  docs/images/Ui.png
  docs/images/ViewPerformanceList.png
  src/main/java/seedu/command/performance/ViewStudentPerformanceList.java
  src/main/java/seedu/ui/UI.java
Labels: Documentation

#195 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Command.png
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/event/Seminar.java
Labels: Documentation

#201 Benjamin v2.1 DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddAttendance.png
  docs/images/Attendance.png
  docs/images/AttendanceCommandInterpreterFlowChart.png
  docs/images/AttendanceCommandInterpreterSequenceDiagram.png
  docs/images/ClearAttendanceList.png
  docs/images/ClearStudentList.png
  docs/images/EditAttendance.png
  docs/images/FindAttendanceList.png
  docs/images/FindStudentList.png
  docs/images/SortAttendanceListByName.png
  docs/images/SortAttendanceListByStatus.png
  docs/images/SortStudentListByList.png
  docs/images/SortStudentListByName.png
  docs/images/Student.png
  docs/images/StudentCommandInterpreterFlowChart.png
  docs/images/StudentList.png
  docs/images/ViewAttendanceList.png
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/EditAttendance.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/student/FindStudentList.java
  src/main/java/seedu/command/student/SortStudentListByList.java
  src/main/java/seedu/command/student/SortStudentListByName.java
  src/main/java/seedu/student/StudentListCollection.java
Labels: Documentation

#196 Fix static methods related to Calendar
  src/main/java/seedu/command/calendar/Calendar.java
  src/main/java/seedu/command/interpreter/CalendarCommandInterpreter.java
  src/main/java/seedu/parser/CalendarParser.java
  src/main/java/seedu/ui/DisplayTable.java
  src/main/java/seedu/ui/UI.java
Labels: Code Quality

#205 Benjamin PPP
  docs/team/benchan911.md
Labels: Documentation

#204 PPP
  docs/team/lowjiayee.md
Labels: Documentation

#236 [StudentList] Bugs Fixed
  docs/UserGuide.md
  src/main/java/seedu/command/student/AddStudentList.java
  src/main/java/seedu/command/student/DeleteStudentList.java
  src/main/java/seedu/command/student/FindStudentList.java
  src/main/java/seedu/ui/DisplayList.java
Labels: type.Bug

#232 [Attendance] Bugs fixed
  docs/UserGuide.md
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/EditAttendance.java
Labels: type.Bug

#235 UGDG and calendar error message issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/harithadiv.md
  src/main/java/seedu/parser/CalendarParser.java
Labels: Documentation, error handling

#244 adding studentCommandInterpreter SequenceDiagram
  docs/DeveloperGuide.md
  docs/images/StudentCommandInterpreterSequenceDiagram.png
  docs/team/benchan911.md
Labels: Documentation

#250 Changes for CS2101
  docs/UserGuide.md
Labels: Documentation
