Repository AY1920S2-CS2113T-T12-4/tp, pull requests merged in 2020-03, with the labels that each got.

#58 Allow space-separated strings to be added to 1 parameter
  src/main/java/seedu/command/event/EditName.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/event/Seminar.java
  src/main/java/seedu/parser/EventParser.java
  src/test/java/seedu/event/EventTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#67 Anqi student list
  Duke.log
  src/main/java/seedu/StudentList.java
  src/main/java/seedu/command/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformance.java
  src/main/java/seedu/command/performance/DeletePerformance.java
  src/main/java/seedu/command/performance/ListStudentPerformance.java
  src/main/java/seedu/command/performance/ViewAssignmentResult.java
  src/main/java/seedu/command/performance/ViewStudentResult.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/parser/AttendanceParser.java
  src/main/java/seedu/parser/PerformanceParser.java
  src/main/java/seedu/performance/Performance.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/ACTUAL.TXT
Labels: feature.new

#78 Change how Events are shown
  Duke.log
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/event/Seminar.java
  text-ui-test/ACTUAL.TXT
Labels: feature.edit

#76 Guide Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Documentation

#73 Anqi performance- working and linked to eventlist
  src/main/java/seedu/command/CommandInterpreter.java
  src/main/java/seedu/command/Help.java
  src/main/java/seedu/command/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformance.java
  src/main/java/seedu/command/performance/DeletePerformance.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/UI.java
Labels: feature.edit

#74 removed Storage
  src/main/java/seedu/parser/ParserStorage.java
  src/main/java/seedu/storage/Storage.java
Labels: feature.edit

#72 Benjamin student command
  src/main/java/seedu/StudentList.java
  src/main/java/seedu/command/CommandInterpreter.java
  src/main/java/seedu/command/StudentCommandInterpreter.java
  src/main/java/seedu/command/student/AddStudent.java
  src/main/java/seedu/command/student/DeleteStudent.java
  src/main/java/seedu/command/student/ListStudent.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/ui/UI.java
Labels: feature.new

#75 added Attendance Functionalities
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/attendance/AddAttendance.java
  src/main/java/seedu/command/attendance/DeleteAttendance.java
  src/main/java/seedu/command/attendance/ListAttendance.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/parser/AttendanceParser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/attendance/AttendanceTest.java
  text-ui-test/ACTUAL.TXT
Labels: feature.edit

#77 Minor Modifications to Event & Seminar
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/event/Seminar.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/event/EventTest.java
  src/test/java/seedu/event/SeminarTest.java
  text-ui-test/ACTUAL.TXT
Labels: feature.edit

#81 Enable Assertion
  build.gradle
Labels: Assertion, error handling

#79 Branch calendar
  src/main/java/seedu/calendar/AddFirstSemester.java
  src/main/java/seedu/calendar/AddSecondSemester.java
  src/main/java/seedu/calendar/CalendarList.java
  src/main/java/seedu/command/CalendarCommandInterpreter.java
  src/main/java/seedu/command/CommandInterpreter.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/parser/CalendarParser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/event/EventTest.java
  src/test/java/seedu/event/SeminarTest.java
Labels: feature.new, severity.Low

#84 Add UG and DG for Event
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/event.png
Labels: Documentation

#93 Anqi - DG format
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/command/performance/DeletePerformance.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/UI.java
Labels: Documentation

#91 Fix text-ui-test
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: feature.edit

#82 Update JUnit
  src/main/java/seedu/attendance/AttendanceList.java
  src/test/java/seedu/attendance/AttendanceListTest.java
  src/test/java/seedu/attendance/AttendanceTest.java
Labels: J unit test

#96 added Attendance Component
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Documentation

#94 Anqi UI - Refactor package.
  src/main/java/seedu/StudentList.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/calendar/CalendarList.java
  src/main/java/seedu/command/Help.java
  src/main/java/seedu/command/event/DeleteEvent.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/CalendarCommandInterpreter.java
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/EventCommandInterpreter.java
  src/main/java/seedu/command/interpreter/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformance.java
  src/main/java/seedu/command/performance/DeletePerformance.java
  src/main/java/seedu/command/student/AddStudent.java
  src/main/java/seedu/command/student/DeleteStudent.java
  src/main/java/seedu/command/student/ListStudent.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/parser/AttendanceParser.java
  src/main/java/seedu/performance/PerformanceList.java
  src/main/java/seedu/ui/DisplayList.java
  src/main/java/seedu/ui/DisplayTable.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#90 Fix event-related issues
  src/main/java/seedu/command/interpreter/EventCommandInterpreter.java
  src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/parser/EventParser.java
Labels: type.Bug

#111 Various fixes to Event & its child classes
  src/main/java/seedu/command/event/EditVenue.java
  src/main/java/seedu/command/event/ListEvent.java
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/EventCommandInterpreter.java
  src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/Seminar.java
  src/main/java/seedu/parser/EventParser.java
  src/main/java/seedu/ui/UI.java
Labels: error handling, type.Bug

#98 Edit Attendance
  src/main/java/seedu/StudentList.java
  src/main/java/seedu/StudentListCollection.java
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendance.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/ClearAttendanceList.java
  src/main/java/seedu/command/attendance/ListAttendance.java
  src/main/java/seedu/command/attendance/SortAttendanceListByName.java
  src/main/java/seedu/command/attendance/SortAttendanceListByStatus.java
  src/main/java/seedu/command/attendance/ViewAttendanceList.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/command/student/AddStudentList.java
  src/main/java/seedu/command/student/ClearStudentList.java
  src/main/java/seedu/command/student/DeleteStudent.java
  src/main/java/seedu/command/student/DeleteStudentList.java
  src/main/java/seedu/command/student/FindStudentList.java
  src/main/java/seedu/command/student/ListStudent.java
  src/main/java/seedu/command/student/SortStudentListByList.java
  src/main/java/seedu/command/student/SortStudentListByName.java
  src/main/java/seedu/command/student/ViewStudentList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/AttendanceParser.java
  src/main/java/seedu/parser/StudentListStorageParser.java
  src/main/java/seedu/ui/DisplayList.java
  src/main/java/seedu/ui/DisplayTable.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/attendance/AttendanceListTest.java
  src/test/java/seedu/attendance/AttendanceTest.java
Labels: feature.edit, feature.new

#113 Updated Documentation
  docs/UserGuide.md
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/command/attendance/SortAttendanceListByName.java
  src/main/java/seedu/command/attendance/SortAttendanceListByStatus.java
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/command/student/DeleteStudentList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/attendance/AttendanceListTest.java
  src/test/java/seedu/attendance/AttendanceTest.java
Labels: Documentation

#108 Implement storage
  .gitignore
  build.gradle
  src/main/java/seedu/StudentList.java
  src/main/java/seedu/StudentListCollection.java
  src/main/java/seedu/attendance/Attendance.java
  src/main/java/seedu/attendance/AttendanceList.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/event/DateTime.java
  src/main/java/seedu/event/Event.java
  src/main/java/seedu/parser/CalendarParser.java
  src/main/java/seedu/performance/Performance.java
  src/main/java/seedu/storage/FileIO.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/attendance/AttendanceListTest.java
  src/test/java/seedu/attendance/AttendanceTest.java
  src/test/java/seedu/duke/DukeTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: type.Enhancement

#115 Bugs fix - student
  src/main/java/seedu/command/attendance/AddAttendanceList.java
  src/main/java/seedu/ui/UI.java
Labels: type.Bug

#112 CommandInterpreter Unit Tests
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/EventCommandInterpreter.java
  src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java
  src/main/java/seedu/parser/EventParser.java
  src/test/java/seedu/interpreter/CommandInterpreterTest.java
  src/test/java/seedu/interpreter/EventCommandInterpreterTest.java
  src/test/java/seedu/interpreter/SeminarCommandInterpreterTest.java
Labels: J unit test

#121 Update User Interface
  data/eventlist.txt
  data/studentlist.txt
  src/main/java/seedu/command/interpreter/AttendanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/CommandInterpreter.java
  src/main/java/seedu/command/interpreter/PerformanceCommandInterpreter.java
  src/main/java/seedu/command/interpreter/StudentCommandInterpreter.java
  src/main/java/seedu/command/performance/AddPerformance.java
  src/main/java/seedu/command/student/AddStudentList.java
  src/main/java/seedu/command/student/DeleteStudentList.java
  src/main/java/seedu/event/EventList.java
  src/main/java/seedu/student/StudentList.java
  src/main/java/seedu/ui/UI.java
Labels: type.Enhancement

#123 Reformat the Developer Guide to improve Readability: Added Content Page
  docs/DeveloperGuide.md
Labels: Documentation
